version: 2
updates:
  - package-ecosystem: maven
    directory: /apps/api
    open-pull-requests-limit: 20
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: daily
    ignore:
      - dependency-name: "@angular*"
      - dependency-name: "@nx*"
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: /
    open-pull-requests-limit: 20
    schedule:
      interval: daily
