name: E2E

on:
  push:
  pull_request:
  workflow_call:
  workflow_dispatch:
    inputs:
      save-video:
        description: 'Save Video'
        required: false
        default: false
        type: boolean

jobs:
  e2e:
    runs-on: ubuntu-latest
    env:
      dependabot-run: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Sync PR with target
        if: github.event_name == 'pull_request'
        run: git merge origin/${{ github.event.pull_request.base.ref }}

      - name: Get branch names
        id: branch-name
        uses: tj-actions/branch-names@v8

      - name: Use Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
            ~/.npm
            ./node_modules
            ./node
            ./nx
          key: ${{ runner.os }}-deps-${{ github.run_id }}
          restore-keys: |
            ${{ runner.os }}-deps-

      - name: Java Dependencies
        working-directory: apps/api
        run: mvn -B dependency:resolve dependency:resolve-plugins

      - name: Node Dependencies
        run: yarn install

      - name: Build
        uses: MansaGroup/nrwl-nx-action@v3
        with:
          targets: build
          all: 'true'
          parallel: 'true'

      - name: E2E
        uses: MansaGroup/nrwl-nx-action@v3
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          CYPRESS_SAVE_VIDEO: ${{ inputs.save-video }}
        with:
          targets: e2e
          projects: api
          parallel: 'false'

      - name: Merge E2E Reports
        if: env.dependabot-run == 'false' && always()
        run: |
          sudo chown -R 1001:1001 ./coverage/apps/app-e2e
          npm run test:merge:e2e

      - name: E2E Test Execution Report
        uses: frango9000/test-execution-report@v0.0.2
        if: env.dependabot-run == 'false' && always()
        with:
          name: E2E Tests
          path: coverage/apps/app-e2e/merged-e2e.xml
          reporter: java-junit
          fail-on-error: false

      - name: Upload E2E Output
        if: failure() || inputs.save-video == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: e2e-output
          path: coverage/apps/app-e2e
